version: "3.1"

services:
  lambda-zookeeper:
    container_name: lambda-zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181

  lambda-kafka:
    container_name: lambda-kafka
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: lambda-kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: lambda-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CREATE_TOPICS: message-ingestion:3:1
    depends_on:
      - lambda-zookeeper
